[WIP]feat(reward): implement BEP-176: Validator Reward Model 2.0
bnb-chain/bsc-genesis-contract pull request #217
Opened 2022-12-14 16:53 UTC by GalaIO

# BEP-176: Validator Reward Model 2.0

- [BEP-176: Validator Reward Model 2.0](#bep-176-validator-reward-model-20)
  - [1. Summary](#1-summary)
  - [2. Abstract](#2-abstract)
  - [3. Status](#3-status)
  - [4.Motivation](#4motivation)
  - [5. Specification](#5-specification)
    - [5.1 Mechanism \& Governance](#51-mechanism--governance)
  - [6. License](#6-license)

## 1. Summary

This BEP will introduce a new validator reward model on BNB Smart Chain. As a result of this BEP, the validator staking reward policy is going to be modified such that it is more accurately representative of the validator's contribution to the overall network.

## 2. Abstract

The mechanism for validator income distribution will be altered when this BEP is implemented. The specifics are still being worked out, but in general, we may divide the overall rewards from gas fees into two parts:
- Network Verification Reward: will be distributed among all validators more equitably, according to their contributions to the whole network.
- Block Reward: The single producer for its work on this block.

The proportion of each part is up for debate, and validators will have the possibility to alter the value through governance.

The idea suggests that we may favor a slightly greater ratio of the Network Verification Reward vs Block Rewards, given that the primary objective is to validate the network to enable real and secure transactions. Our viewpoint is that transactions are resources shared among validators; a validator should not consider them to be their property.

## 3. Status

Draft

## 4.Motivation
Before this BEP, the validator’s reward mostly relied on the transaction gas fee it received, as their only source of rewards is the gas fee for the transaction in the blocks they produce. A validator will get more rewards if it packs more transactions into the block it produces. It was designed to encourage validators to add more transactions, but it didn’t represent the overall contribution that a validator made. In general opinion, a validator should be rewarded even if it only produces empty blocks, because it helps build the network, e.g. verify blocks, keep a copy of the latest network storage state, broadcast blocks and transactions… But validator will lose its dedicated block reward if it produces empty block, so it still encourages validator to add more transactions in its block.

The rewards logic will serve multiple objectives. In addition to transaction inclusion, it is necessary to consider efforts to validate blocks and maintain network security.

Absolute fairness is not an easy goal to accomplish, but we do our best to bring about some improvements with this BEP. We name it Validator Reward Model 2.0, it could have further revisions to keep improving it.

## 5. Specification
Currently, as defined by the Parlia consensus, block producers will collect the gas fee of each transaction as its reward and distribute it to a system contract temporarily.
The system contract will forward the reward information to Beacon Chain periodically to settle the reward along with the staking information kept on Beacon Chain.

The general procedure will not be changed in this BEP, but 2 steps will be added:
- For each block, part of the block reward will be put into the shared network contribution funding pool. Initially, the ratio is set to 50%, i.e. half of the rewards will be shared with the other validators.
- Before the system contracts forward the reward information to Beacon Chain, the funding pool will be distributed according to the network contribution of each validator. The contribution could be simply determined by the block number it produces.

### 5.1 Mechanism & Governance

A governable parameters: **validatorRewardRatio** will be introduced in the ValidatorSet Contract. At the end of each block, the Validator will sign a transaction to invoke the deposit function of the contract to transfer the gas fee. The validator reward model logic is implemented within the deposit function that: **validatorRewardRatio * ( gasFee - burnRatio*gasFee)**  will be transferred to the validator contribution funding pool address;

The initial setting:
- validatorRewardRatio = 50%

This process will be carried on BNB Beacon Chain, every community member can propose a change of the params. The proposal needs to receive a minimum deposit of BNB (2000BNB on mainnet for now, refundable after the proposal has passed) so that the validators can vote for it. The validators of BSC can vote for it or against it based on their staking amount of BNB.

If the total voting power of bounded validators that votes for it reaches the quorum (50% on mainnet), the proposal will pass and the corresponding change of the params will be passed onto BSC via cross-chain communication and take effect immediately. The vote of unbounded validators will not be considered into the tally.

## 6. License

The content is licensed under [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

2022-12-26 09:02 UTC, guagualvcha commented on contracts/BSCValidatorSet.sol
> +  event validatorSharing(address indexed validator, uint256 amount);
`rewardShared` is a bit better than `validatorSharing`? Seems we follow a pattern to define event like `event somethingDone ...`,  some word like `Sharing` which means `doing` is not a proper word here.

2022-12-26 09:06 UTC, guagualvcha commented on contracts/BSCValidatorSet.sol
> +    if (sharingRewardPercent > SHARING_REWARD_SCALE || SHARING_REWARD_SCALE == 0) {
`SHARING_REWARD_SCALE == 0` seems unnecessary, it is a const rather than a var and it won't happen.

2022-12-26 09:13 UTC, guagualvcha commented on contracts/BSCValidatorSet.sol
> +    extra.slots[0] = 0;
Please set `extra.slots[0] = 0` inside `function jailValidator(Validator memory v) internal returns (uint32)`

2022-12-26 09:17 UTC, GalaIO commented
Notice: the PR is ready for review, but maybe not be merged into develop branch instantly, should wait for BEP-176 merged first. 

This PR is just a reference implementation of https://github.com/bnb-chain/BEPs/pull/176. Thanks for your time to review it.

2022-12-27 08:38 UTC, brilliant-lx reviewed
maybe some of the naming could be improved, e.g. `dedicatedReward ` -> `blockReward `, `sharing` -> `share`?

2022-12-27 08:46 UTC, brilliant-lx commented on contracts/BSCValidatorSet.sol
> +          uint256 addition = sharingRewardFundingPool.mul(validatorExtraSet[i].slots[0]).div(totalBlockCount);
what is the precision of `div` in solidity?, `3/4 ==> 0 or 1?`

2022-12-27 08:47 UTC, brilliant-lx commented on contracts/BSCValidatorSet.sol
> +      // reset sharingFundingPool, and left token in sharingFundingPool will send to systemReward automatically.
there could be some fragment left, not divide-able, is it ok to discard it?

2022-12-27 08:50 UTC, brilliant-lx commented on contracts/BSCValidatorSet.sol
> +  bool public sharingRewardInitialized;
can we move this init operation into constructer?

2023-02-28 05:15 UTC, alice22foster requested changes
changes

2023-04-01 11:37 UTC, Nelyydavid4 approved these changes

2023-04-01 11:45 UTC, Nelyydavid4 approved these changes

2023-04-01 11:50 UTC, Nelyydavid4 approved these changes

2023-06-29 21:56 UTC, Clifforddu approved these changes

2023-11-29 08:59 UTC, zjubfd commented
This will need furthuer discussion, close first.

2023-11-29 08:59 UTC, closed without merging

2023-11-30 02:47 UTC, Clifforddu commented
Reply to sign off for release of my latest rewards. Thank you and God bless Kind Regards Clifford DumontOn Nov 29, 2023, at 3:59 AM, zjubfd ***@***.***> wrote:﻿
Closed #217.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>